# --------------------------------------------------------
# TRITON RACER T7 - DOCKERFILE
# Target: Raspberry Pi 5 (ARM64) | OS: ROS 2 Humble
# --------------------------------------------------------
    FROM ros:humble-ros-base
    
    # 1. INSTALL SYSTEM TOOLS
    # Added 'asio-cmake-module' and 'io-context' to fix the dependency chain error
    RUN apt-get update && apt-get install -y \
        python3-pip \
        python3-vcstool \
        python3-colcon-common-extensions \
        cmake \
        libapr1-dev \
        libpcl-dev \
        ros-humble-cv-bridge \
        ros-humble-vision-opencv \
        ros-humble-depthai-ros \
        ros-humble-ackermann-msgs \
        ros-humble-serial-driver \
        ros-humble-asio-cmake-module \
        ros-humble-io-context \
        libusb-1.0-0-dev \
        git \
        build-essential \
        && rm -rf /var/lib/apt/lists/*
    
    # 2. INSTALL PYTHON AI LIBRARIES
    RUN pip3 install \
        numpy \
        opencv-python \
        scipy \
        ultralytics \
        depthai \
        blobconverter

    # 3. SETUP WORKSPACE
    WORKDIR /race_ws
    COPY docker/racer.repos .
    
    # 4. DOWNLOAD REPOS (copy local src first so vcs import does not get overwritten)
    RUN mkdir -p src
    COPY src ./src
    RUN vcs import . < racer.repos

    # Init submodules (ackermann_mux, vesc, teleop_tools) inside f1tenth_system
    RUN git -C /race_ws/src/f1tenth_system submodule update --init --recursive

    # 5. BUILD THE SYSTEM
    RUN source /opt/ros/humble/setup.sh && \
        colcon build --sy
