ackermann_mux:
  ros__parameters:
    topics:
      # Autonomy (wall_follow_node) publishes AckermannDriveStamped here:
      navigation:
        topic: /drive
        timeout: 0.2
        priority: 10

      # Joystick teleop publishes AckermannDriveStamped here (manual override):
      joystick:
        topic: /teleop
        timeout: 0.2
        priority: 100
