ackermann_mux:
  ros__parameters:
    topics:
      # Your autonomy node publishes AckermannDriveStamped here:
      navigation:
        topic: /ackermann_mux/input/nav_0
        timeout: 0.2
        priority: 10

      # Joystick teleop publishes AckermannDriveStamped here (manual override):
      joystick:
        topic: /teleop
        timeout: 0.2
        priority: 100
